name: Process Startups with OpenAI

on:
  workflow_dispatch:   # lets you run manually from Actions tab

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install openai

      - name: Run startup processor
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/process_startups.py

      - name: Commit updated GeoJSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add nl_earlystage_map.geojson
          git commit -m "Update startup list with OpenAI" || echo "No changes to commit"
          git push
